_target_: src.models.diffusion_module.DiffusionModule 

diffusion_model: 
  _target_: src.models.diffusion.net.conditional_diffusion.ConditionalDiffusion

  denoise_net: 
    _target_: src.models.components.UNet.UNet
    in_ch: 1 
    t_emb_dim: 256 
    c_emb_dim: 256 
    num_classes: 10 
  time_steps: 1000 
  schedule: 'cosine'

sampler: 
  _target_: src.models.diffusion.sampler.ddim.DDIMSampler
  diffusion_model: ${model.diffusion_model}
  num_samples: 100
  image_size: 32 
  channels: 1 
  reduce_steps: 50 
  device: 'cuda'

optimizer:
  _target_: torch.optim.Adam 
  _partial_: True
  lr: 1e-4
