_target_: src.models.diffusion_module.DiffusionModule 
diffusion_model: 
  _target_: src.models.net.unconditional_diffusion.UnconditionalDiffusion
  denoise_net: 
    _target_: src.models.components.UNet.UNet
    inp_ch: 1 
    t_emb_dim: 256 
  time_steps: 1000 
  schedule: 'cosine'
optimizer: torch.optim.Adam 
