_target_: src.models.flowmatching_module.FlowMatchingModule 

num_steps: 1000
velocity_model: 
  _target_: src.models.flow_matching.flow_matching.VelocityModel
  image_size: 128
  channel: 1
  net: 
    _target_: src.models.components.UNet.UNet
    in_ch: 1 
    t_emb_dim: 256
    base_channel: 32
    multiplier: [1, 2, 4, 8]
    type_condition: "continuous_label"
    use_discrete_time: False
    use_attention: False
optimizer:
  _target_: torch.optim.Adam 
  _partial_: True
  lr: 1e-5

use_condition: True
w: 4.0
