_target_: src.models.srdiffusion_module.SRDiffusionModule 

diffusion_model: 
  _target_: src.models.diffusion.net.sr_diffusion.SRDiffusion 
  vae_module_path: '/mnt/apple/k66/hanh/diffusion/logs/train/runs/kl_vae_3x64x64v0/KL_VAE/wzopack4/checkpoints/epoch=74-step=450000.ckpt'
  denoise_net: 
    _target_: src.models.components.UNet_No_Attn.UNetNoAttn 
    in_ch: 3 
    t_emb_dim: 256 
    type_condition: 'image_sr' 
  time_steps: 200
  schedule: 'cosine' 

sampler: 
  _target_: src.models.diffusion.sampler.ddpm.DDPMSampler 
  diffusion_model: ${model.diffusion_model} 
  num_samples: 4 
  image_size: 64 
  channels: 3 
  step_collect: 10
  device: 'cuda' 

optimizer: 
  _target_: torch.optim.Adam 
  _partial_: True 
  lr: 1e-5 



  