_target_: src.models.srdiffusion_module.SRDiffusion

diffusion_model: 
  _target_: src.models.diffusion.net.diffusion.Diffusion

  encoder: 
    _target_: src.models.vae.components.Encoder.Encoder

    in_ch: 3
    z_ch: 3 
    base_ch: 64 
    multiplier: [1, 2, 4] 
    double_latent: True
  
  decoder: 
    _target_: src.models.vae.components.Decoder.Decoder 

    out_ch: 3
    z_ch: 3 
    base_ch: 64 
    multiplier: [4, 2, 1]

  extractor: 
    _target_: src.models.vae.components.FeatureExtractor.FeatureExtractor
  
  kld_weight: 1e-6 

  feature_weight: 0.006

optimizer: 
  _target_: torch.optim.Adam 
  _partial_: True
  lr: 1e-5 