_target_: src.models.vae_module.VAEModule

vae_model: 
  _target_: src.models.vae.net.kl_vae.KLVAEModel

  encoder: 
    _target_: src.models.vae.components.Encoder.Encoder

    in_ch: 3
    z_ch: 3 
    base_ch: 64
    multiplier: [1, 2, 4] 
    double_latent: True 

  decoder: 
    _target_: src.models.vae.components.Decoder.Decoder 

    out_ch: 3
    z_ch: 3 
    base_ch: 64
    multiplier: [4, 2, 1] 
  
  kld_weight: 1e-6

  # quantizer: 
  #   _target_: src.models.vae.components.Quantizer.Quantizer 

  #   num_embeds: 1024
  #   embed_dim: 3 
  #   beta: 0.25 


optimizer:
  _target_: torch.optim.Adam 
  
  _partial_: True
  lr: 1e-5